export function bgData() {
    return [
        bg("Anomia", 2, "J"),
        bg("Archipelago", 4, "J"),
        bg("Arkham Horror: The Card Game", 2, "A"),
        bg("AuZtralia", 4, "J"),
        bg("Battlestar Galactica", 4, "J"),
        bg("Biblios", 2, "A"),
        bg("Black Orchestra", 4, "J"),
        bg("Bloodbourne", 2, "J"),
        bg("Chaos Marauders", 2, "J"),
        bg("Chinatown", 2, "A"),
        bg("Concordia", 5, "J"),
        bg("Dark Souls", 4, "M"),
        bg("Deep Sea Adventure", 1, "A"),
        bg("Eclipse", 5, "A"),
        bg("Empires", 2, "J"),
        bg("Escape the Dark Castle", 1, "J"),
        bg("Fallen Land", 1, "J"),
        bg("Fort", 3, "A"),
        bg("Fortress America", 5, "J"),
        bg("Fury of Dracula", 3, "J"),
        bg("Glorantha: The Gods War", 3, "J"),
        bg("Imperial Assault", 4, "J"),
        bg("Legendary Encounters: Alien", 3, "J"),
        bg("Lord of the Rings", 3, "J"),
        bg("Lord of the Rings: Journeys in Middle-earth", 4, "J"),
        bg("Lowlands", 4, "J"),
        bg("Mansions of Madness", 3, "J"),
        bg("Mice and Mystics", 3, "J"),
        bg("Modern Art", 2, "A"),
        bg("Oceans", 4, "A"),
        bg("On Mars", 5, "A"),
        bg("Parks", 2, "A"),
        bg("Pax Pamir", 4, "A"),
        bg("Puerto Rico", 0, "T"),
        bg("Root", 4, "A"),
        bg("Seafall", 3, "J"),
        bg("Secret Hitler", 2, "J"),
        bg("Scythe", 5, "J"),
        bg("Sprawlopolis", 2, "A"),
        bg("Star Wars: Outer Rim", 3, "J"),
        bg("Startups", 2, "A"),
        bg("Super Munchkin", 0, "T"),
        bg("Terraforming Mars", 5, "T"),
        bg("Tussie Mussie", 1, "A"),
        bg("Underwater Cities", 5, "A"),
        bg("Unmatched: BoL Vol 1", 2, "A"),
        bg("Unmatched: Bruce Lee", 2, "A"),
        bg("Unmatched: Cobble & Fog", 2, "A"),
        bg("Unmatched: Ingen vs Raptors", 2, "A"),
        bg("Unmatched: Robin Hood vs Bigfoot", 2, "A"),
        bg("Vinhos", 5, "A"),
    ]
}

function bg(name, complexity, owner) {
    return {
        "name": name,
        "complexity": complexity,
        "owner": owner
    }
}
